version: 2.1
jobs:
  compile:
   docker:
      - image: xyzuan/xdocker:latest
   steps:
      - run:
          command: |
           git config --global user.name "fazrul1994"
           git config --global user.email "fazrulfadhilah@gmail.com"
           git clone https://github.com/fazrul1994/xDroneCi circle
           cd circle
           apt install bc \
            binutils-dev \
            bison \
            build-essential \
            ca-certificates \
            ccache \
            clang \
            cmake \
            curl \
            file \
            flex \
            git \
            libelf-dev \
            libssl-dev \
            lld \
            make \
            ninja-build \
            python3-dev \
            texinfo \
            u-boot-tools \
            xz-utils \
            zlib1g-dev \
            lld -y
           bash .circleci/compile.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
